trying to fix gsl version number; install now fails

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1694,8 +1694,8 @@ echo "$as_me: error: gsl-config not found, is GSL installed?" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-{ echo "$as_me:$LINENO: checking if GSL version >= 1.12" >&5
-echo $ECHO_N "checking if GSL version >= 1.12... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking if GSL version >= 2.0" >&5
+echo $ECHO_N "checking if GSL version >= 2.0... $ECHO_C" >&6; }
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2676,8 +2676,8 @@ fi
 
 
 if test "${gsl_version_ok}" = no; then
-  { { echo "$as_me:$LINENO: error: Need GSL version >= 1.12" >&5
-echo "$as_me: error: Need GSL version >= 1.12" >&2;}
+  { { echo "$as_me:$LINENO: error: Need GSL version >= 2.0" >&5
+echo "$as_me: error: Need GSL version >= 2.0" >&2;}
    { (exit 1); exit 1; }; }
 else
   { echo "$as_me:$LINENO: result: yes" >&5
